version: '3'

vars:
  VERSION:
    sh: git describe --tags
  TIMESTAMP:
    sh: "date --rfc-3339='seconds' --utc"

tasks:
  _require_sudo:
    cmds:
      - echo "Confirming you have sudo privileges..."
      - sudo echo "test" > /dev/null
    silent: true

  _registry_auth:
    cmds:
      - echo "Confirming you have authenticated with the registry..."
      - sudo docker login ghcr.io/museus
    silent: true

  build:
    dir: deploy
    vars:
      TIMESTAMP:
        sh: "date --rfc-3339='seconds' --utc"
    sources:
      - ../src
    cmds:
      - task: _require_sudo
      - printf '\nBuilding {{ .VERSION }} at {{ .TIMESTAMP }}\n\n'
      - sudo BUILD_VERSION="{{ .VERSION }}" docker compose build --build-arg BUILD_TIMESTAMP="{{ .TIMESTAMP }}"

  push:
    dir: deploy
    cmds:
      - task: _require_sudo
      - task: _registry_auth
      - task: build
      - sudo BUILD_VERSION="{{ .VERSION }}" docker compose push
    silent: true

  inspect:
    deps: [_require_sudo]
    cmds:
      - sudo docker inspect ghcr.io/museus/supportiveshade:latest

  deploy:
    dir: deploy
    cmds:
      - sudo BUILD_VERSION="{{ .VERSION }}" docker compose up -d
