
services:
    bot:
        image: "supportive-shade"
        build:
            context: ../src
            dockerfile: Dockerfile
            args:
                BUILD_TIMESTAMP: "$BUILD_TIMESTAMP"

        env_file:
            - path: ./.env
              required: true

        volumes:
          - ./config.toml:/etc/supportive_shade/config.toml
          - data:/var/lib/supportive_shade

volumes:
  data:

