name: Build and push image

on:
  push:

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Git describe
        id: ghd
        uses: proudust/gh-describe@v2
      -
        name: Get build timestamp
        id: timestamp
        run: echo "timestamp=$(date --rfc-3339='seconds' --utc)" >> "$GITHUB_OUTPUT"
      -
        name: Get escaped branch name
        id: escape-branch
        run: echo "branch_name=${{ github.ref_name }} | sed 's/\//-/g'" >> "$GITHUB_OUTPUT"

      -
        name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
        env:
          BRANCH_NAME: ${{ steps.escape-branch.outputs.branch_name }}
          COMMIT_SHA: ${{ github.sha }}
          BUILD_VERSION: ${{ steps.ghd.outputs.describe }}
          BUILD_TIMESTAMP: ${{ steps.timestamp.outputs.timestamp }}
